Open media
mitel-networks/micc-api-samples pull request #1
Opened 2017-02-13 17:28 UTC by danishsaj

Could you please review the changes/additions? Thanks!

2017-02-13 20:22 UTC, danishsaj commented
Hi Test!

2017-02-13 20:43 UTC, quinton-j requested changes
See comments in the review.  Some minor changes required.

2017-02-13 20:43 UTC, quinton-j commented on common/micc.js
> +		this.postRequest(`openmedia`, body, processResponse);
Correct the indentation of this line.

2017-02-13 20:43 UTC, quinton-j commented on common/micc.js
> +		this.postRequest(`openmedia`, body, processResponse);
Correct indentation.

2017-02-13 20:43 UTC, quinton-j commented on openMediaVideoConferencing/openMediaVideoConferencing.html
> +</html>
Correct indentation.

2017-02-13 20:43 UTC, quinton-j commented on openMediaVideoConferencing/openMediaVideoConferencing.js
> +    );
Correct indentation.

2017-02-13 20:43 UTC, quinton-j commented on openMediaVideoConferencing/openMediaVideoConferencing.js
> +}
Correct indentation.

2017-02-13 20:43 UTC, quinton-j commented on openMediaVideoConferencing/openMediaVideoConferencing.js
> +            }
Correct indentation.

2017-02-13 20:43 UTC, quinton-j commented on openMediaVideoConferencing/readme.md
> +
We should chat about the sample name.  Is openMediaVideoConferencing the right name?  Maybe we call it just openMedia to start.  Or openMediaAppearIn?  Let's round up and chat when you've updated the other comments.

2017-02-15 13:49 UTC, quinton-j requested changes
We're close.  A couple minor tweaks and it's ready.

2017-02-15 13:49 UTC, quinton-j commented on openMediaAppearIn/readme.md
> +Basic demo of open media conversation routing by glueing [appear.in](https://appear.in/)
We should should use the 'integrate with' rather than 'glueing" (which is spelled wrong).

2017-02-15 13:49 UTC, quinton-j commented on openMediaAppearIn/openMediaAppearIn.html
> +    <script src="openMediaVideoConferencing.js"></script>
This file name no longer matches the js file name.  Retest application to ensure in good working order since changes.

2017-02-16 02:26 UTC, danishsaj commented on openMediaAppearIn/readme.md
> +Basic demo of open media conversation routing by glueing [appear.in](https://appear.in/)
Changed it to: ... routing through integration with appear.in

Some references for the spelling of 'glueing': 
[thefreedictionary](http://www.thefreedictionary.com/glueing)
[merriam-webster](https://www.merriam-webster.com/dictionary/glue)

2017-02-16 12:37 UTC, merged